import { useGLTF } from "@react-three/drei";

import streetsScene from "../assets/road.glb";
import { useRef } from "react";
import { RigidBody } from "@react-three/rapier";

const Streets = (props) => {
  const { scene } = useGLTF(streetsScene);
  console.log(scene)
  const ref = useRef();
  return (
    <RigidBody colliders='cuboid' type='fixed'>
      <mesh {...props} ref={ref}>
        <primitive object={scene} />
      </mesh>
    </RigidBody>
  );
};

export default Streets;

// /* eslint-disable react/no-unknown-property */
// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Author: 99.Miles (https://sketchfab.com/99.Miles)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/free-city-road-layout-mockup-3260e3fef3434939bc8df94a0a15ead3
// Title: [FREE] City Road Layout Mockup
// */

// import { useGLTF } from "@react-three/drei";

// import streetsScene from '../assets/streets.glb'
// import { useRef } from "react";
// import { RigidBody } from "@react-three/rapier";

// const Streets =(props) => {
//   const { nodes, materials } = useGLTF(streetsScene);
//   const ref = useRef();
//   console.log(props)
//   return (
//     <RigidBody colliders='trimesh' type='fixed' >
//     <group {...props}ref={ref} dispose={null}>
//       <group scale={0.01}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Road001_ROAD_MARKINGS_0.geometry}
//           material={materials.ROAD_MARKINGS}
//           position={[-210978.469, -5576.756, -202094.109]}
//           rotation={[-Math.PI / 2, 0, 0]}
//           scale={100}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Road002_OLD_SIDEWALK_TRIMSHEET_0.geometry}
//           material={materials.OLD_SIDEWALK_TRIMSHEET}
//           position={[-210978.469, -5576.756, -202094.109]}
//           rotation={[-Math.PI / 2, 0, 0]}
//           scale={100}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Road003_GRASS_0.geometry}
//           material={materials.GRASS}
//           position={[-210978.469, -5576.756, -202094.109]}
//           rotation={[-Math.PI / 2, 0, 0]}
//           scale={100}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Road004_ROAD_WEAR_TRANSPARENT_0.geometry}
//           material={materials.ROAD_WEAR_TRANSPARENT}
//           position={[-210978.469, -5576.756, -202094.109]}
//           rotation={[-Math.PI / 2, 0, 0]}
//           scale={100}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Road005_GENERIC_SIDEWALKS_0.geometry}
//           material={materials.GENERIC_SIDEWALKS}
//           position={[-210978.469, -5576.756, -202094.109]}
//           rotation={[-Math.PI / 2, 0, 0]}
//           scale={100}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Road006_ROAD_WORNED_0.geometry}
//           material={materials.ROAD_WORNED}
//           position={[-210978.469, -5576.756, -202094.109]}
//           rotation={[-Math.PI / 2, 0, 0]}
//           scale={100}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Road007_BIKE_LANES_0.geometry}
//           material={materials.BIKE_LANES}
//           position={[-210978.469, -5576.756, -202094.109]}
//           rotation={[-Math.PI / 2, 0, 0]}
//           scale={100}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Road008_ROAD_NEW_0.geometry}
//           material={materials.ROAD_NEW}
//           position={[-210978.469, -5576.756, -202094.109]}
//           rotation={[-Math.PI / 2, 0, 0]}
//           scale={100}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Road009_ROAD_GENERIC_0.geometry}
//           material={materials.ROAD_GENERIC}
//           position={[-210978.469, -5576.756, -202094.109]}
//           rotation={[-Math.PI / 2, 0, 0]}
//           scale={100}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Road010_CROSSINGS_0.geometry}
//           material={materials.CROSSINGS}
//           position={[-210978.469, -5576.756, -202094.109]}
//           rotation={[-Math.PI / 2, 0, 0]}
//           scale={100}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Road011_ASPHALT_BARE_0.geometry}
//           material={materials.ASPHALT_BARE}
//           position={[-210978.469, -5576.756, -202094.109]}
//           rotation={[-Math.PI / 2, 0, 0]}
//           scale={100}
//         />
//       </group>
//     </group>
//     </RigidBody>
//   );
// }

// useGLTF.preload(streetsScene);

// export default Streets;
